name: env-gene

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip

  # Core scientific python
  - numpy
  - scipy
  - pandas

  # Plotting
  - matplotlib

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse

  # pip requirements for Coalescent theory libs
  - pip:
      - msprime
